In [1]:
import numpy as np
import pandas as pd

In [2]:
def grad(x):
    return x**2 + 6*np.sin(x)

def cost(x):
    return 2*x + 6*np.cos(x)

def gradient_descent(x0, learning_rate, iterations):
    x = [x0]
    for i in range(iterations):
        x_new = x[-1] - learning_rate * cost(x[-1])
        if abs(grad(x_new)) < 1e-3:
            break
        x.append(x_new)
    return (x, i)

x0 = 0
learning_rate = 0.001
iterations = 1000000

results, num_iterations = gradient_descent(x0, learning_rate, iterations)

df = pd.DataFrame({'Iteration': range(len(results)),
                   'x Value': results})

df

         Iteration   x Value
0                0  0.000000
1                1 -0.006000
2                2 -0.011988
3                3 -0.017963
4                4 -0.023927
...            ...       ...
999996      999996 -1.170121
999997      999997 -1.170121
999998      999998 -1.170121
999999      999999 -1.170121
1000000    1000000 -1.170121

[1000001 rows x 2 columns]